name: OOC
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - appnope=0.1.2
  - apscheduler=3.10.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=23.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bs4=4.11.1
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - cryptography=41.0.3
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - h11=0.12.0
  - h2=4.0.0
  - hpack=4.0.0
  - httpcore=0.15.0
  - httpx=0.23.3
  - hyperframe=6.0.1
  - idna=3.4
  - importlib-metadata=7.0.0
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=7.4.9
  - jupyter_core=5.5.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.2.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nb_conda_kernels=2.3.1
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1w
  - packaging=23.1
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-telegram-bot=20.1
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyzmq=23.2.0
  - readline=8.2
  - redis-py=4.3.4
  - referencing=0.30.2
  - requests=2.28.1
  - rfc3986=1.4.0
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.5
  - spotipy=2.22.1
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - tzlocal=5.2
  - urllib3=1.26.18
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - wrapt=1.14.1
  - xz=5.4.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
