name: OOC
channels:
  - conda-forge
  - defaults
dependencies:
  - spotipy==2.22.1
  - python-telegram-bot==20.1
  - python==3.10.9
  - requests==2.28.1
  - numpy==1.23.5
  - pandas==1.5.2
  - nb_conda_kernels==2.3.1
  - bs4==4.11.1
  - ipykernel==6.19.2
  - nest-asyncio==1.5.6
  - apscheduler
